
## TODO include here an option for standalone deployment or limit parallelism

## Service type for most components
serviceType: ClusterIP

## Controller is exposed in a LoadBalancer
controllerServiceType: LoadBalancer

## KubeML image
image: centaurusinfra/kubeml
kubemlVersion: "test.0.1.10"



# work for the following command
#kubemlVersion: "latest"

#imageVersion: "0.2"


## Storage service image
storageImage: centaurusinfra/kubeml-storage-svc

## Namespace for the images
namespace: kubeml

## Configuration for the environment in which functions will run
## this is a fission CRD with a custom image and dependencies already installed
environment:
  defaultName: torch
  poolsize: 10
  cpuMin: 100m
  cpuMax: 1000m
  image: centaurusinfra/serverless-python-env
  imageVersion: "1.0.1"
  gracePeriod: 5
  version: 3



## Instructions for mongo deployment
mongo:
  serviceType: ClusterIP
  serviceName: mongodb

## RedisAI config
redisai:
  serviceType: ClusterIP
  serviceName: redisai


# ## Storage
# localstorage:
#   serviceType: ClusterIP
#   serviceName: localstorage


